name: test bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # 1時間に1回

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests
      - run: python bot.py

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add status.txt
          git commit -m "update status" || true
          git push
